spring:
  profiles:
    active: dev
---
spring:
  kafka:
    consumer:
      bootstrap-servers: 10.16.31.179:9092,10.16.31.180:9092,10.16.31.227:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: defaultGroup
  profiles: dev
app:
  kafka:
    topics:
      - daqWeb
      - gemini
  kudu:
    master: 10.16.31.227
    table-mappings:
      daqWeb.t_order: daqWeb.t_order
    queue-size: 10
  buffer:
    init-size: 3
logging:
  level:
    com.guoanshequ.synchronizer.data: debug
---
spring:
  kafka:
    consumer:
      bootstrap-servers: 10.30.0.12:9092,10.30.0.13:9092,10.30.0.14:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: defaultGroup
  profiles: pro
app:
  kafka:
    topics:
      - gemini
  kudu:
    master: 10.30.0.13
    table-mappings:
      gemini.t_order: gemini.t_order
    queue-size: 10
  buffer:
    init-size: 3
logging:
  level:
    com.guoanshequ.synchronizer.data: info