spring:
  profiles:
    active: test
---
spring:
  kafka:
    consumer:
      bootstrap-servers: 10.16.31.179:9092,10.16.31.180:9092,10.16.31.227:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: defaultGroup
  profiles: dev
app:
  kafka:
    topics:
      - gemini
  kudu:
    master: 10.16.31.227
    table-mappings:
      gemini.t_order: gemini.t_order
      gemini.t_order_item: gemini.t_order_item
      gemini.t_customer: gemini.t_customer
    queue-size: 10
  buffer:
    init-size: 3
logging:
  level:
    com.guoanshequ.synchronizer.data: debug
  file: data-sender.log
---
spring:
  kafka:
    consumer:
      bootstrap-servers: 10.16.31.179:9092,10.16.31.180:9092,10.16.31.227:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: defaultGroup
  profiles: test
app:
  kafka:
    topics:
      - gemini
  kudu:
    master: 10.16.31.227
    table-mappings:
      gemini.t_order: gemini.t_order
      gemini.t_order_item: gemini.t_order_item
      gemini.t_customer: gemini.t_customer
      gemini.t_employee: gemini.t_employee
    queue-size: 10
  buffer:
    init-size: 3
logging:
  level:
    com.guoanshequ.synchronizer.data: info
  file: data-sender.log
---
spring:
  kafka:
    consumer:
      bootstrap-servers: 10.30.0.12:9092,10.30.0.13:9092,10.30.0.14:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: defaultGroup
  profiles: pro
app:
  kafka:
    topics:
      - gemini
  kudu:
    master: 10.30.0.13
    table-mappings:
      gemini.t_order: gemini.t_order
      gemini.t_order_item: gemini.t_order_item
      gemini.t_customer: gemini.t_customer
      gemini.t_employee: gemini.t_employee
    queue-size: 10
  buffer:
    init-size: 3
logging:
  level:
    com.guoanshequ.synchronizer.data: info
  file: data-sender.log